# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c56d3c4d3c4d958ee6f151debcabb421ec3640d8e778c703af56909c1643f0ac8a3d81db8a4bbb28e0bd1210fe532ff05c6825655af06fdefdf211f633d385

test:
  secret_key_base: c849e09baad7d7577335afa0769b3ed540957fa34bbb0d3955321eb87a5bd9589067000837095ae982c28d1a93774e4729ca6979699679aa659eee342fa7b460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
